trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- powershell: |
    $GITHUB_HOST="https://"+"$(Build.Repository.Uri)".split("/")[2]
    Write-Output "Host : $GITHUB_HOST"
    $codeql_runner_url = "https://github.com/github/codeql-action/releases/download/codeql-bundle-20210421/codeql-runner-win.exe"
    $codeql_runner_output_file = "$PSScriptRoot\codeql-runner-win.exe"
    try
    {
        $Response = Invoke-WebRequest -Uri $codeql_runner_url -OutFile $codeql_runner_output_file
        $StatusCode = $Response.StatusCode
        Write-Output "Download completed successfully"
    }
    catch
    {
        $StatusCode = $_.Exception.Response.StatusCode.value__
        Write-Output "Download Failed"
    }
  displayName: 'Download CodeQL Runner and Binary'

- powershell: |
    $GITHUB_HOST="https://"+"$(Build.Repository.Uri)".split("/")[2]
    $codeql_runner_output_file = "$PSScriptRoot\codeql-runner-win.exe"
    & $codeql_runner_output_file init --repository $(Build.Repository.Name) --github-url $GITHUB_HOST --github-auth $(GITHUB_PAT)
    # . codeql-runner/codeql-env.sh
    # <BUILD STEPS GO HERE>
    & $codeql_runner_output_file analyze --repository $(Build.Repository.Name) --github-url $GITHUB_HOST --github-auth $(GITHUB_PAT) --commit $(Build.SourceVersion) --ref $(Build.SourceBranch)
  displayName: 'CodeQL Scan'
